on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

name: vignette

env:
  cache-version: "cache-v1"

jobs:
  vignette:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        config:
          - { os: macos-latest }
    runs-on: ${{ matrix.config.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        id: install-r
        with:
          bioc-version: release

      - name: Get R version
        id: R
        run: |
          R --version > VERSION
          echo "version=$(head -1 VERSION | awk '{print $3}')" >> $GITHUB_OUTPUT
        shell: bash -l {0}

      - name: Get Bioconductor version
        id: BIOC
        run: |
          echo "version=$R_BIOC_VERSION" >> $GITHUB_OUTPUT
        shell: bash -l {0}

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: /home/runner/work/_temp/Library
          key: ${{ env.cache-version }}-${{ matrix.config.os }}-biocversion-${{ steps.BIOC.outputs.version}}-r-${{ steps.R.outputs.version}}-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ env.cache-version }}-${{ matrix.config.os }}-biocversion-${{ steps.BIOC.outputs.version}}-r-${{ steps.R.outputs.version}}-

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: pkgdown

      - name: Install package
        run: R CMD INSTALL .

      - name: Build and deploy pkgdown site
        if: github.actor == 'zktuong' && github.repository == 'zktuong/ktplots'
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
        shell: bash -l {0}
